2020-04-07 14:58:52.655 [error] <0.195.0>@client:handle_info:50 gen_server client terminated with reason: no match of right hand value {error,econnrefused} in client:handle_info/2 line 50
2020-04-07 14:58:52.655 [error] <0.195.0>@client:handle_info:50 CRASH REPORT Process client with 2 neighbours crashed with reason: no match of right hand value {error,econnrefused} in client:handle_info/2 line 50
2020-04-07 15:02:55.865 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},exit,badarg,undefined,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,142}]},{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},...]}}
2020-04-07 15:06:32.913 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},exit,badarg,undefined,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,142}]},{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},...]}}
2020-04-07 15:08:19.688 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},exit,badarg,undefined,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,142}]},{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},...]}}
2020-04-07 15:12:42.713 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},error,{'module could not be loaded',utils},undefined,[{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},{gen_event,server_update,...},...]}}
2020-04-07 15:13:46.363 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},error,{'module could not be loaded',utils},undefined,[{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},{gen_event,server_update,...},...]}}
2020-04-07 15:24:54.950 [error] <0.119.0>@player_sup:start_link:34 <0.119.0> 1111111
2020-04-07 15:24:54.952 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},exit,badarg,undefined,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,142}]},{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,55}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},...]}}
2020-04-07 15:29:55.376 [error] <0.111.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[etcp_listener,{undefined,undefined},exit,badarg,undefined,[{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,142}]},{etcp_listener,init,1,[{file,"h:/erl_ws/etcp/_build/default/lib/etcp/src/etcp_listener.erl"},{line,53}]},{gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,697}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]]},[{error_logger_lager_h,log_event,2,[{file,"h:/erl_ws/etcp/_build/default/lib/lager/src/error_logger_lager_h.erl"},{line,205}]},...]}}
2020-04-07 15:31:44.638 [error] <0.145.0>@etcp_listener:accepting:107 gen_statem etcp_listener in state accepting terminated with reason: no case clause matching <0.157.0> in etcp_listener:accepting/3 line 107
2020-04-07 15:31:44.638 [error] <0.145.0>@etcp_listener:accepting:107 CRASH REPORT Process etcp_listener with 0 neighbours crashed with reason: no case clause matching <0.157.0> in etcp_listener:accepting/3 line 107
2020-04-07 15:31:44.638 [error] <0.124.0>@etcp_listener:accepting:107 Supervisor etcp_sup had child {listener_sup,{player,8111}} started with etcp_listener:start_link({8111,[binary,{packet,raw}],player_sup,player,#Fun<etcp.1.5024299>}) at <0.145.0> exit with reason no case clause matching <0.157.0> in etcp_listener:accepting/3 line 107 in context child_terminated
